# Generated by Django 5.2.7 on 2025-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyMemcache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Memcached Stats',
                'verbose_name_plural': 'Memcached Stats',
                'managed': False,
            },
        ),
    ]
